# Generated by Django 4.2.16 on 2026-06-16 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='工序名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='工序编号')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='产品名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='产品编号')),
                ('spec', models.CharField(blank=True, max_length=200, verbose_name='规格')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='工单号')),
                ('quantity', models.IntegerField(verbose_name='生产数量')),
                ('deadline', models.DateField(verbose_name='交付截止日期')),
                ('status', models.CharField(choices=[('pending', '待生产'), ('in_progress', '生产中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('has_report', models.BooleanField(default=False, verbose_name='是否已有报工')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '生产工单',
                'verbose_name_plural': '生产工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reported_quantity', models.IntegerField(default=0, verbose_name='已报工数量')),
                ('passed_quantity', models.IntegerField(default=0, verbose_name='质检合格数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.process', verbose_name='工序')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='api.workorder', verbose_name='工单')),
                ('workers', models.ManyToManyField(related_name='assigned_processes', to=settings.AUTH_USER_MODEL, verbose_name='指派工人')),
            ],
            options={
                'verbose_name': '工单工序',
                'verbose_name_plural': '工单工序',
                'ordering': ['process__id'],
                'unique_together': {('work_order', 'process')},
            },
        ),
    ]
