# Generated by Django 4.2.16 on 2026-06-16 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_process_product_workorder_workorderprocess'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='报工数量')),
                ('status', models.CharField(choices=[('pending', '待质检'), ('passed', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='状态')),
                ('inspection_time', models.DateTimeField(blank=True, null=True, verbose_name='质检时间')),
                ('inspection_remark', models.TextField(blank=True, verbose_name='质检备注')),
                ('remark', models.TextField(blank=True, verbose_name='报工备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inspected_reports', to=settings.AUTH_USER_MODEL, verbose_name='质检人')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='api.workorder', verbose_name='工单')),
                ('work_order_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='api.workorderprocess', verbose_name='工单工序')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_reports', to=settings.AUTH_USER_MODEL, verbose_name='报工工人')),
            ],
            options={
                'verbose_name': '报工记录',
                'verbose_name_plural': '报工记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
