# Generated by Django 4.2.16 on 2026-06-16 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_workreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='is_locked',
            field=models.BooleanField(default=False, verbose_name='是否锁定'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='parent_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rework_reports', to='api.workreport', verbose_name='原报工记录'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='passed_quantity',
            field=models.IntegerField(default=0, verbose_name='合格件数'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='rework_quantity',
            field=models.IntegerField(default=0, verbose_name='返工件数'),
        ),
        migrations.AddField(
            model_name='workreport',
            name='scrapped_quantity',
            field=models.IntegerField(default=0, verbose_name='报废件数'),
        ),
        migrations.AlterField(
            model_name='workreport',
            name='status',
            field=models.CharField(choices=[('pending', '待质检'), ('passed', '已通过'), ('rejected', '已驳回'), ('rework', '待返工')], default='pending', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ReworkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='返工数量')),
                ('status', models.CharField(choices=[('pending', '待返工'), ('submitted', '已提交重检'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('resubmitted_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_rework_tasks', to='api.workreport', verbose_name='重新提交的报工记录')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_tasks', to='api.workorder', verbose_name='工单')),
                ('work_order_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_tasks', to='api.workorderprocess', verbose_name='工单工序')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_tasks', to='api.workreport', verbose_name='原报工记录')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rework_tasks', to=settings.AUTH_USER_MODEL, verbose_name='返工工人')),
            ],
            options={
                'verbose_name': '返修任务',
                'verbose_name_plural': '返修任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
