# Generated by Django 4.2.16 on 2026-06-16 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_workreport_is_locked_workreport_parent_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalarySettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settlement_month', models.CharField(max_length=7, verbose_name='结算月份(YYYY-MM)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='总金额')),
                ('total_workers', models.IntegerField(default=0, verbose_name='工人总数')),
                ('total_reports', models.IntegerField(default=0, verbose_name='报工记录总数')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('settled', '已结算')], default='settled', max_length=20, verbose_name='状态')),
                ('is_final', models.BooleanField(default=True, verbose_name='是否最终结算(锁定数据)')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_settlements', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '工资结算单',
                'verbose_name_plural': '工资结算单',
                'ordering': ['-created_at'],
                'unique_together': {('settlement_month', 'is_final')},
            },
        ),
        migrations.CreateModel(
            name='SalarySettlementDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed_quantity', models.IntegerField(default=0, verbose_name='合格件数')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='单价(4位小数)')),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=12, verbose_name='小计(4位小数)')),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='最终金额(2位小数)')),
                ('report_created_at', models.DateTimeField(verbose_name='报工时间')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.salarysettlement', verbose_name='结算单')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_details', to='api.workorder', verbose_name='工单')),
                ('work_order_process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_details', to='api.workorderprocess', verbose_name='工单工序')),
                ('work_report', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlement_details', to='api.workreport', verbose_name='报工记录')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_details', to=settings.AUTH_USER_MODEL, verbose_name='工人')),
            ],
            options={
                'verbose_name': '工资结算明细',
                'verbose_name_plural': '工资结算明细',
                'ordering': ['worker__name', '-report_created_at'],
            },
        ),
    ]
