# Generated by Django 4.2.16 on 2026-06-17 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_salarysettlement_salarysettlementdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='默认工价'),
        ),
        migrations.CreateModel(
            name='ProductProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0, verbose_name='工序顺序')),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='计件单价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.process', verbose_name='工序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_processes', to='api.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品工序',
                'verbose_name_plural': '产品工序',
                'ordering': ['product__id', 'order_index'],
                'unique_together': {('product', 'process')},
            },
        ),
    ]
